"""Generate and validate the capture harness's node spec — plan T1.4 → T2.1.

``moe_trace`` hardcodes no tensor names. It reads a ``key=value`` spec file, and this module is what
produces one from ``configs/models.yaml``. So T1.4's discovery output is *data*: a model whose graph
turns out to name things differently needs a config edit, not a recompile.

The routing chain in llama.cpp master
-------------------------------------
Read from ``llm_graph_context::build_moe_ffn`` in ``src/llama-graph.cpp``::

    logits = build_lora_mm(gate_inp, cur)          -> cb "ffn_moe_logits"        [n_expert, n_tok]
    if (gate_inp_b)  logits += gate_inp_b          -> cb "ffn_moe_logits_biased"
    probs  = gating_op(logits)                     -> cb "ffn_moe_probs"
    if (exp_probs_b) selection_probs = probs + b   -> cb "ffn_moe_probs_biased"
    if (n_expert_groups > 1) group mask            -> cb "ffn_moe_probs_masked"
    selected_experts = ggml_argsort_top_k(selection_probs, n_expert_used)
                                                   -> cb "ffn_moe_argsort" (parent)
                                                   -> cb "ffn_moe_topk"    (view, I32)

**Top-k does not run on the logits.** It runs on the last node of that chain. For softmax, sigmoid
and sqrt-softplus gating the transform is monotonic, so the *ordering* — and therefore ``topk.bin``
— is unaffected. But ``exp_probs_b`` (DeepSeek-V3's selection bias) and group masking are **not**
order-preserving, and ``gate_inp_b`` (GPT-OSS's router bias) changes the ordering relative to the
unbiased logits. Hence :func:`selection_chain`: the tensor to capture into ``logits.bin`` is the
*last* node that exists, because that is the one whose k vs k+1 margin actually decided selection —
which is what Phase 8's T8.2 flip-rate analysis conditions on.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import yaml

__all__ = [
    "SPEC_FORMAT_VERSION",
    "SELECTION_CHAIN",
    "DEFAULT_NODE_TEMPLATES",
    "NodeSpecError",
    "NodeSpec",
    "layer_index_map",
    "selection_chain",
    "build_spec",
    "resolve_lookup",
    "parse_spec",
]

SPEC_FORMAT_VERSION = 1

SELECTION_CHAIN: tuple[str, ...] = (
    "ffn_moe_logits",
    "ffn_moe_logits_biased",
    "ffn_moe_probs",
    "ffn_moe_probs_biased",
    "ffn_moe_probs_masked",
)
"""The selection chain, earliest to latest. The *last* present node is what top-k consumed."""

UNSUPPORTED_ARCHS: dict[str, str] = {
    # Verified against src/llama-graph.cpp at commit 7077abbe: both of these reassign
    # `selection_probs` after the chain has already been named, so "last node present" is wrong.
    "llama4": "selection_probs is reset to the raw logits with no cb() of its own",
    "grovemoe": "selection_probs is a second sigmoid of the logits, cb'd as ffn_moe_probs_biased",
}
"""Architectures whose selection tensor leaves the documented chain. Refused, never guessed."""

DEFAULT_NODE_TEMPLATES: dict[str, str] = {
    "topk": "ffn_moe_topk-%d",
    "logits": "ffn_moe_probs-%d",
    # The router input is `cur` as passed into build_moe_ffn, which most architectures cb as
    # "ffn_norm" one line earlier. It is the *normalized* hidden state, which is exactly what
    # plan §1.3/C10 requires F4/F5/FV to condition on -- and why the FV probe (>=0.99) is the
    # end-to-end validation that this name is right for a given model.
    "router_input": "ffn_norm-%d",
}
"""A **hypothesis**, not a fact. T1.4 confirms it per model with ``llama-eval-callback -ngl 0``."""


class NodeSpecError(Exception):
    """The spec is incomplete or internally inconsistent. Never a warning: T1.4 is a halt gate."""


@dataclass
class NodeSpec:
    model: str
    n_moe_layers: int
    n_experts: int
    top_k: int
    hidden_dim: int
    layer_map: list[int]
    node_topk: str
    node_logits: str
    node_router_input: str
    verified: bool = False
    notes: list[str] = field(default_factory=list)

    def render(self) -> str:
        """The ``key=value`` text the C++ side parses."""
        lines = [
            "# GENERATED by src/capture/nodespec.py -- do not edit by hand.",
            f"# model={self.model}  verified_by_T1.4={str(self.verified).lower()}",
        ]
        lines += [f"# {n}" for n in self.notes]
        lines += [
            f"format_version={SPEC_FORMAT_VERSION}",
            f"model={self.model}",
            f"n_moe_layers={self.n_moe_layers}",
            f"n_experts={self.n_experts}",
            f"top_k={self.top_k}",
            f"hidden_dim={self.hidden_dim}",
            "layer_index_map=" + ",".join(str(i) for i in self.layer_map),
            f"node_topk={self.node_topk}",
            f"node_logits={self.node_logits}",
            f"node_router_input={self.node_router_input}",
            "",
        ]
        return "\n".join(lines)

    def write(self, path: Path | str) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(), encoding="ascii")
        return path


# -- layer mapping ------------------------------------------------------------------------------


def layer_index_map(config: Mapping[str, Any]) -> list[int]:
    """Trace layer → llama.cpp ``il``.

    DeepSeek-V2-Lite has ``first_k_dense_replace: 1``, so its model layer 0 is dense and trace
    layer 0 is model layer **1**. An identity map would mislabel every layer while producing files
    of exactly the right size — plan T3.5 exists to catch that, and this is where it is prevented.
    """
    offset = int(config.get("moe_layer_offset", 0) or 0)
    n = int(config["n_moe_layers"])
    if n < 1:
        raise NodeSpecError(f"n_moe_layers must be >= 1, got {n}")
    if offset < 0:
        raise NodeSpecError(f"moe_layer_offset must be >= 0, got {offset}")

    freq = int(config.get("moe_layer_freq", 1) or 1)
    if freq != 1:
        # offset + contiguous range is only the right map when every layer from the offset on is
        # MoE. DeepSeek's moe_layer_freq interleaves dense layers, and nothing downstream could
        # detect the resulting off-by-one: the files would be exactly the right size with every
        # layer mislabelled. Refuse rather than emit a map that is quietly wrong.
        raise NodeSpecError(
            f"moe_layer_freq={freq} means MoE layers are not contiguous from the offset; "
            "layer_index_map must be written out explicitly for this model"
        )
    return [offset + i for i in range(n)]


# -- selection chain -----------------------------------------------------------------------------


def selection_chain(config: Mapping[str, Any]) -> tuple[list[str], str]:
    """Predict the chain of named nodes and which one top-k consumes.

    Returns ``(present_nodes, selection_node)``. A prediction only: T1.4 confirms it by recomputing
    top-k from the captured tensor and comparing against ``topk.bin`` on 1k tokens.
    """
    arch = str(config.get("arch") or "").lower()
    if arch in UNSUPPORTED_ARCHS:
        raise NodeSpecError(
            f"architecture {arch!r} routes outside the documented selection chain "
            f"({UNSUPPORTED_ARCHS[arch]}), so the last node of the chain is NOT what top-k "
            "consumed. Refusing to emit a logit_tensor_used that would silently name the wrong "
            "tensor. No panel model uses this arch; adding one requires re-reading build_moe_ffn."
        )

    present = ["ffn_moe_logits"]
    if config.get("has_router_bias"):
        present.append("ffn_moe_logits_biased")  # gate_inp_b — GPT-OSS
    present.append("ffn_moe_probs")
    if config.get("has_expert_selection_bias"):
        present.append("ffn_moe_probs_biased")  # exp_probs_b — DeepSeek-V3 style
    if int(config.get("n_expert_groups", 1) or 1) > 1:
        # Group masking also emits `ffn_moe_group_topk` (the surviving group indices). It is not on
        # the selection chain -- the masked probs are -- but it is worth capturing as a diagnostic if
        # a grouped model ever enters the panel, since it explains which experts were unreachable.
        present.append("ffn_moe_probs_masked")
    return present, present[-1]


# -- spec construction ----------------------------------------------------------------------------


def build_spec(
    model_key: str,
    models: Mapping[str, Any],
    *,
    assume_defaults: bool = False,
) -> NodeSpec:
    """Build a spec for one model from a loaded ``configs/models.yaml``.

    With ``assume_defaults=False`` (the default) an unfilled ``node_names`` block is a hard error:
    T1.4 is a halt gate and guessing node names is exactly what it exists to prevent. Pass
    ``assume_defaults=True`` only to produce the *hypothesis* spec that T1.4 itself checks — the
    result is stamped ``verified_by_T1.4=false``.
    """
    try:
        config = models["models"][model_key]
    except KeyError as exc:
        raise NodeSpecError(
            f"{model_key!r} is not in models.yaml; have {sorted(models.get('models', {}))}"
        ) from exc

    names = dict(config.get("node_names") or {})
    declared = {k: v for k, v in names.items() if v}
    notes: list[str] = []

    if declared.get("topk") and declared.get("router_input"):
        node_topk = declared["topk"]
        node_router = declared["router_input"]
        # `logit_tensor_used` is the *record* of which node selection consumed — a bare node base
        # name, because that is what T8.2 and the paper quote. `node_names.logits` is the capture
        # *template*. They must agree, and disagreeing is a config error worth halting on: it means
        # the stream would be filled from one node while the writeup names another.
        used = config.get("logit_tensor_used")
        if not used:
            raise NodeSpecError(
                f"{model_key}: node_names is filled but logit_tensor_used is not. Which tensor "
                "logits.bin came from must be recorded — the margin is only interpretable if it "
                "is the margin selection actually ran on (plan §1.6, T8.2)."
            )
        node_logits = declared.get("logits") or f"{used}-%d"
        if node_logits.split("-%d")[0] != used:
            raise NodeSpecError(
                f"{model_key}: node_names.logits={node_logits!r} does not name "
                f"logit_tensor_used={used!r}. logits.bin would be filled from one node while the "
                "results record another."
            )
        verified = True
    elif assume_defaults:
        _, selection = selection_chain(config)
        node_topk = DEFAULT_NODE_TEMPLATES["topk"]
        node_router = DEFAULT_NODE_TEMPLATES["router_input"]
        node_logits = f"{selection}-%d"
        verified = False
        notes.append(
            "UNVERIFIED hypothesis from llama.cpp master build_moe_ffn. T1.4 must confirm with "
            "llama-eval-callback -ngl 0 -c 512 before this spec is used to collect."
        )
        notes.append(f"predicted selection node: {selection}")
    else:
        missing = [k for k in ("topk", "router_input") if not declared.get(k)]
        raise NodeSpecError(
            f"{model_key}: node_names {missing} are unset. T1.4 (node-name discovery) is a HALT "
            "GATE and must run before capture. Use assume_defaults=True only to generate the "
            "hypothesis spec that T1.4 checks."
        )

    for label, template in (
        ("node_topk", node_topk),
        ("node_logits", node_logits),
        ("node_router_input", node_router),
    ):
        if template.count("%d") != 1:
            raise NodeSpecError(
                f"{model_key}: {label}={template!r} must contain exactly one '%d' layer placeholder"
            )

    spec = NodeSpec(
        model=model_key,
        n_moe_layers=int(config["n_moe_layers"]),
        n_experts=int(config["n_experts"]),
        top_k=int(config["top_k"]),
        hidden_dim=int(config["hidden_dim"]),
        layer_map=layer_index_map(config),
        node_topk=node_topk,
        node_logits=node_logits,
        node_router_input=node_router,
        verified=verified,
        notes=notes,
    )
    resolve_lookup(spec)  # raises on a name collision
    return spec


def resolve_lookup(spec: NodeSpec) -> dict[str, tuple[str, int, int]]:
    """``{tensor_name: (stream, trace_layer, model_layer)}`` — mirrors the C++ map exactly.

    Kept in Python as well as C++ so the rule is testable before the harness can be built, and so a
    collision (two streams resolving to the same tensor, which would double-write one stream and
    leave another empty) is caught at generation time rather than mid-collection.
    """
    if spec.top_k > spec.n_experts:
        raise NodeSpecError(f"{spec.model}: top_k={spec.top_k} exceeds n_experts={spec.n_experts}")
    if len(spec.layer_map) != spec.n_moe_layers:
        raise NodeSpecError(
            f"{spec.model}: layer_index_map has {len(spec.layer_map)} entries but n_moe_layers="
            f"{spec.n_moe_layers}"
        )
    if len(set(spec.layer_map)) != len(spec.layer_map):
        raise NodeSpecError(f"{spec.model}: layer_index_map has duplicate model layers")

    lookup: dict[str, tuple[str, int, int]] = {}
    templates = (
        ("topk", spec.node_topk),
        ("logits", spec.node_logits),
        ("router_input", spec.node_router_input),
    )
    for trace_layer, model_layer in enumerate(spec.layer_map):
        for stream, template in templates:
            name = template.replace("%d", str(model_layer))
            if name in lookup:
                other = lookup[name]
                raise NodeSpecError(
                    f"{spec.model}: streams {other[0]!r} and {stream!r} both resolve to tensor "
                    f"{name!r}. One stream would be written twice and another left empty."
                )
            lookup[name] = (stream, trace_layer, model_layer)
    return lookup


def parse_spec(text: str) -> NodeSpec:
    """Read back a rendered spec. Round-trip coverage for the C++ parser's contract."""
    kv: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise NodeSpecError(f"malformed spec line (no '='): {line}")
        key, value = line.split("=", 1)
        kv[key.strip()] = value.strip()

    version = kv.get("format_version")
    if version != str(SPEC_FORMAT_VERSION):
        raise NodeSpecError(f"unsupported spec format_version: {version!r}")

    required = (
        "model",
        "n_moe_layers",
        "n_experts",
        "top_k",
        "hidden_dim",
        "layer_index_map",
        "node_topk",
        "node_logits",
        "node_router_input",
    )
    missing = [k for k in required if not kv.get(k)]
    if missing:
        raise NodeSpecError(f"spec is missing key(s): {missing}")

    spec = NodeSpec(
        model=kv["model"],
        n_moe_layers=int(kv["n_moe_layers"]),
        n_experts=int(kv["n_experts"]),
        top_k=int(kv["top_k"]),
        hidden_dim=int(kv["hidden_dim"]),
        layer_map=[int(p) for p in kv["layer_index_map"].split(",") if p.strip()],
        node_topk=kv["node_topk"],
        node_logits=kv["node_logits"],
        node_router_input=kv["node_router_input"],
        verified="verified_by_T1.4=true" in text,
    )
    resolve_lookup(spec)
    return spec


# -- CLI --------------------------------------------------------------------------------------------


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate a moe_trace node spec (plan T1.4/T2.1)")
    parser.add_argument("--models", default="configs/models.yaml")
    parser.add_argument("--model", required=True, help="model key, or 'all'")
    parser.add_argument("--out-dir", default="configs/nodes")
    parser.add_argument(
        "--assume-defaults",
        action="store_true",
        help="emit the UNVERIFIED llama.cpp-master hypothesis for T1.4 to check",
    )
    args = parser.parse_args(argv)

    models = yaml.safe_load(Path(args.models).read_text(encoding="utf-8"))
    keys = sorted(models["models"]) if args.model == "all" else [args.model]

    for key in keys:
        spec = build_spec(key, models, assume_defaults=args.assume_defaults)
        path = spec.write(Path(args.out_dir) / f"{key}.spec")
        flag = "verified" if spec.verified else "UNVERIFIED (T1.4 pending)"
        print(f"{path}  layers={spec.n_moe_layers} map={spec.layer_map[0]}..{spec.layer_map[-1]}  {flag}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
