// GENERATED by src/traces/format.py - do not edit by hand.
// Regenerate:  python -m src.traces.format --emit-header src/capture/trace_format.h
//
// The Python reader and this header are produced from one definition so that the capture
// binary and the analysis code cannot disagree about the on-disk layout.

#pragma once
#include <stdint.h>

#define MOE_TRACE_FORMAT_VERSION 1

// tokens.bin - one record per token, in corpus order.
typedef struct {
    uint32_t token_id;
    uint32_t doc_id;
    uint32_t pos_in_doc;
    uint32_t flags;        // bit0: router input captured into hidden.bin
} moe_token_record;

#define MOE_FLAG_HIDDEN_CAPTURED 1
#define MOE_TOKEN_RECORD_BYTES   16

// Element types, asserted per stream in the callback (plan T2.2 rule 3).
//   topk.bin    <- GGML_TYPE_I32   (4 B per index)
//   NOTE: casting the topk buffer to `const float *` produces garbage SILENTLY.
//   logits.bin  <- GGML_TYPE_F32 source, written as float16 (2 B)
//   hidden.bin  <- GGML_TYPE_F32 source, written as float16 (2 B)
#define MOE_TOPK_ELEM_BYTES   4
#define MOE_LOGIT_ELEM_BYTES  2
#define MOE_HIDDEN_ELEM_BYTES 2
#define MOE_HIDDEN_INDEX_ELEM_BYTES 4

// Per-token strides. Both topk and logits are LAYER-MAJOR WITHIN TOKEN.
#define MOE_TOPK_STRIDE(n_layers, top_k)        ((size_t)(n_layers) * (top_k) * MOE_TOPK_ELEM_BYTES)
#define MOE_LOGIT_STRIDE(n_layers, n_experts)   ((size_t)(n_layers) * (n_experts) * MOE_LOGIT_ELEM_BYTES)
#define MOE_HIDDEN_STRIDE(n_layers, hidden_dim) ((size_t)(n_layers) * (hidden_dim) * MOE_HIDDEN_ELEM_BYTES)

static const char * const MOE_FILE_TOKENS       = "tokens.bin";
static const char * const MOE_FILE_TOPK         = "topk.bin";
static const char * const MOE_FILE_LOGITS       = "logits.bin";
static const char * const MOE_FILE_HIDDEN       = "hidden.bin";
static const char * const MOE_FILE_HIDDEN_INDEX = "hidden_index.bin";
