# GENERATED by src/capture/nodespec.py -- do not edit by hand.
# model=deepseek-v2-lite  verified_by_T1.4=true
format_version=1
model=deepseek-v2-lite
n_moe_layers=26
n_experts=64
top_k=6
hidden_dim=2048
layer_index_map=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26
node_topk=ffn_moe_topk-%d
node_logits=ffn_moe_probs-%d
node_router_input=ffn_norm-%d
