# GENERATED by src/capture/nodespec.py -- do not edit by hand.
# model=gemma-4-26b-a4b  verified_by_T1.4=false
# UNVERIFIED hypothesis from llama.cpp master build_moe_ffn. T1.4 must confirm with llama-eval-callback -ngl 0 -c 512 before this spec is used to collect.
# predicted selection node: ffn_moe_probs
# router_input taken from models.yaml, not predicted: ffn_moe_router_input-%d
format_version=1
model=gemma-4-26b-a4b
n_moe_layers=30
n_experts=128
top_k=8
hidden_dim=2816
layer_index_map=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29
node_topk=ffn_moe_topk-%d
node_logits=ffn_moe_probs-%d
node_router_input=ffn_moe_router_input-%d
