# GENERATED by src/capture/nodespec.py -- do not edit by hand.
# model=gpt-oss-20b  verified_by_T1.4=true
format_version=1
model=gpt-oss-20b
n_moe_layers=24
n_experts=32
top_k=4
hidden_dim=2880
layer_index_map=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
node_topk=ffn_moe_topk-%d
node_logits=ffn_moe_probs-%d
node_router_input=attn_post_norm-%d
