# GENERATED by src/capture/nodespec.py -- do not edit by hand.
# model=olmoe-0125-instruct  verified_by_T1.4=true
format_version=1
model=olmoe-0125-instruct
n_moe_layers=16
n_experts=64
top_k=8
hidden_dim=2048
layer_index_map=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
node_topk=ffn_moe_topk-%d
node_logits=ffn_moe_probs-%d
node_router_input=ffn_norm-%d
